-- ============================================================
-- NexGen Platform — Complete Database Setup
-- Paste this entire file into Supabase SQL Editor and click Run.
-- Safe to run multiple times (idempotent).
-- NO dummy data — only real user/admin blogs will show.
-- ============================================================


-- ============================================================
-- 1. PROFILES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id               UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name        TEXT,
  email            TEXT UNIQUE,
  role             TEXT DEFAULT 'user' CHECK (role IN ('superadmin', 'admin', 'user')),
  balance          DECIMAL(12,2) DEFAULT 0.00,
  total_withdrawn  DECIMAL(12,2) DEFAULT 0.00,
  views_total      BIGINT DEFAULT 0,
  suspended_until  TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  suspension_reason TEXT DEFAULT NULL,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Add any missing columns safely
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='balance')           THEN ALTER TABLE profiles ADD COLUMN balance          DECIMAL(12,2) DEFAULT 0.00; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='total_withdrawn')  THEN ALTER TABLE profiles ADD COLUMN total_withdrawn  DECIMAL(12,2) DEFAULT 0.00; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='views_total')      THEN ALTER TABLE profiles ADD COLUMN views_total      BIGINT DEFAULT 0; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='suspended_until')  THEN ALTER TABLE profiles ADD COLUMN suspended_until  TIMESTAMP WITH TIME ZONE DEFAULT NULL; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='suspension_reason') THEN ALTER TABLE profiles ADD COLUMN suspension_reason TEXT DEFAULT NULL; END IF;
END $$;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 2. FILES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.files (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  type       TEXT,
  size       TEXT,
  url        TEXT,
  author_id  UUID REFERENCES auth.users DEFAULT auth.uid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 3. BLOGS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.blogs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      TEXT NOT NULL,
  category   TEXT NOT NULL,
  excerpt    TEXT,
  content    TEXT,
  date       TEXT,
  author_id  UUID REFERENCES auth.users DEFAULT auth.uid(),
  views      BIGINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Add missing columns safely
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blogs' AND column_name='image_url')   THEN ALTER TABLE blogs ADD COLUMN image_url   TEXT; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blogs' AND column_name='file_id')     THEN ALTER TABLE blogs ADD COLUMN file_id     BIGINT REFERENCES files(id) ON DELETE SET NULL; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blogs' AND column_name='author_name') THEN ALTER TABLE blogs ADD COLUMN author_name TEXT; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blogs' AND column_name='status') THEN
    ALTER TABLE blogs ADD COLUMN status TEXT DEFAULT 'published';
    -- Apply the check constraint only after adding the column
    ALTER TABLE blogs ADD CONSTRAINT blogs_status_check CHECK (status IN ('draft', 'published'));
  END IF;
END $$;

ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 4. HELPER FUNCTIONS
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role IN ('admin', 'superadmin')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'superadmin'
  );
END;
$$;

-- Auto-create profile on new signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    CASE WHEN new.email = 'ishoracharya977@gmail.com' THEN 'superadmin' ELSE 'user' END
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Increment blog views + author's total views
CREATE OR REPLACE FUNCTION public.increment_view_count(blog_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  author_uuid UUID;
BEGIN
  SELECT author_id INTO author_uuid FROM blogs WHERE id = blog_id;
  UPDATE blogs    SET views       = views       + 1 WHERE id          = blog_id;
  UPDATE profiles SET views_total = views_total + 1 WHERE id          = author_uuid;
END;
$$;


-- ============================================================
-- 5. RLS POLICIES — PROFILES
-- ============================================================
DO $$ BEGIN
  DROP POLICY IF EXISTS "Users can read own profile"                  ON profiles;
  DROP POLICY IF EXISTS "Users can insert own profile"                ON profiles;
  DROP POLICY IF EXISTS "Users can update own profile"                ON profiles;
  DROP POLICY IF EXISTS "Admins can read all profiles"                ON profiles;
  DROP POLICY IF EXISTS "Admins can update user roles"                ON profiles;
  DROP POLICY IF EXISTS "Admins can delete users except superadmin"   ON profiles;
END $$;

CREATE POLICY "Users can read own profile"      ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile"    ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile"    ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can read all profiles"    ON profiles FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins can update user roles"    ON profiles FOR UPDATE USING (public.is_superadmin());
CREATE POLICY "Admins can delete users except superadmin" ON profiles FOR DELETE
  USING (public.is_superadmin() AND email <> 'ishoracharya977@gmail.com');


-- ============================================================
-- 6. RLS POLICIES — BLOGS
-- ============================================================
DO $$ BEGIN
  DROP POLICY IF EXISTS "Public Read Published Blogs"  ON blogs;
  DROP POLICY IF EXISTS "Public Read Blogs"            ON blogs;
  DROP POLICY IF EXISTS "Users can insert own blogs"   ON blogs;
  DROP POLICY IF EXISTS "Users can update own blogs"   ON blogs;
  DROP POLICY IF EXISTS "Users can delete own blogs"   ON blogs;
  DROP POLICY IF EXISTS "Admins can update any blog"   ON blogs;
  DROP POLICY IF EXISTS "Admins can delete any blog"   ON blogs;
  DROP POLICY IF EXISTS "Admins can manage all blogs"  ON blogs;
  DROP POLICY IF EXISTS "Superadmin can manage all blogs" ON blogs;
END $$;

-- Public visitors see published blogs + legacy NULL-status blogs + own drafts
CREATE POLICY "Public Read Published Blogs" ON blogs FOR SELECT
  USING (status = 'published' OR status IS NULL OR auth.uid() = author_id OR public.is_admin());

CREATE POLICY "Users can insert own blogs"  ON blogs FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Users can update own blogs"  ON blogs FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Users can delete own blogs"  ON blogs FOR DELETE USING (auth.uid() = author_id);
CREATE POLICY "Admins can update any blog"  ON blogs FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admins can delete any blog"  ON blogs FOR DELETE USING (public.is_admin());


-- ============================================================
-- 7. RLS POLICIES — FILES
-- ============================================================
DO $$ BEGIN
  DROP POLICY IF EXISTS "Users can manage own files"      ON files;
  DROP POLICY IF EXISTS "Superadmin can manage all files" ON files;
  DROP POLICY IF EXISTS "Public Read Files"               ON files;
END $$;

CREATE POLICY "Users can manage own files"      ON files FOR ALL    USING (auth.uid() = author_id);
CREATE POLICY "Superadmin can manage all files" ON files FOR ALL    USING (public.is_superadmin());
CREATE POLICY "Public Read Files"               ON files FOR SELECT USING (true);


-- ============================================================
-- 8. ANALYTICS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.analytics (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id   UUID DEFAULT gen_random_uuid(),
  source       TEXT,
  traffic_type TEXT,
  age_group    TEXT,
  gender       TEXT,
  browser      TEXT,
  device       TEXT,
  location     TEXT,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Public Insert Analytics" ON analytics;
  DROP POLICY IF EXISTS "Admins Read Analytics"   ON analytics;
END $$;

CREATE POLICY "Public Insert Analytics" ON analytics FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins Read Analytics"   ON analytics FOR SELECT USING (public.is_superadmin());


-- ============================================================
-- 9. SUBSCRIBERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.subscribers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      TEXT UNIQUE NOT NULL,
  status     TEXT DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Public Insert Subscribers" ON subscribers;
  DROP POLICY IF EXISTS "Admins Read Subscribers"   ON subscribers;
  DROP POLICY IF EXISTS "Admins Manage Subscribers" ON subscribers;
END $$;

CREATE POLICY "Public Insert Subscribers" ON subscribers FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins Read Subscribers"   ON subscribers FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins Manage Subscribers" ON subscribers FOR ALL    USING (public.is_admin());


-- ============================================================
-- 10. BLOG COMMENTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.blog_comments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_id      BIGINT REFERENCES blogs(id) ON DELETE CASCADE NOT NULL,
  author_name  TEXT NOT NULL,
  author_email TEXT NOT NULL,
  comment_text TEXT NOT NULL,
  status       TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

ALTER TABLE public.blog_comments ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Public Insert Comments"        ON blog_comments;
  DROP POLICY IF EXISTS "Public Read Approved Comments" ON blog_comments;
  DROP POLICY IF EXISTS "Admins Manage Comments"        ON blog_comments;
END $$;

CREATE POLICY "Public Insert Comments"        ON blog_comments FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read Approved Comments" ON blog_comments FOR SELECT
  USING (status = 'approved' OR public.is_admin());
CREATE POLICY "Admins Manage Comments"        ON blog_comments FOR ALL USING (public.is_admin());


-- ============================================================
-- 11. BLOG REACTIONS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.blog_reactions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_id         BIGINT REFERENCES blogs(id) ON DELETE CASCADE NOT NULL,
  reaction_type   TEXT DEFAULT 'like' CHECK (reaction_type IN ('like', 'love', 'insightful')),
  user_identifier TEXT NOT NULL,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  UNIQUE(blog_id, user_identifier, reaction_type)
);

ALTER TABLE public.blog_reactions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Public Insert Reactions"     ON blog_reactions;
  DROP POLICY IF EXISTS "Public Read Reactions"       ON blog_reactions;
  DROP POLICY IF EXISTS "Public Delete Own Reactions" ON blog_reactions;
END $$;

CREATE POLICY "Public Insert Reactions"     ON blog_reactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read Reactions"       ON blog_reactions FOR SELECT USING (true);
CREATE POLICY "Public Delete Own Reactions" ON blog_reactions FOR DELETE USING (true);


-- ============================================================
-- 12. SITE ADS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.site_ads (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url  TEXT NOT NULL,
  link_url   TEXT,
  is_active  BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

ALTER TABLE public.site_ads ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Public Read Ads"   ON site_ads;
  DROP POLICY IF EXISTS "Admins Manage Ads" ON site_ads;
END $$;

CREATE POLICY "Public Read Ads"   ON site_ads FOR SELECT USING (true);
CREATE POLICY "Admins Manage Ads" ON site_ads FOR ALL    USING (public.is_admin());


-- ============================================================
-- 13. CONTACT MESSAGES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL,
  message    TEXT NOT NULL,
  is_read    BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Public Insert Contact Messages" ON contact_messages;
  DROP POLICY IF EXISTS "Admins Read Contact Messages"   ON contact_messages;
  DROP POLICY IF EXISTS "Admins Manage Contact Messages" ON contact_messages;
END $$;

CREATE POLICY "Public Insert Contact Messages" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins Read Contact Messages"   ON contact_messages FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins Manage Contact Messages" ON contact_messages FOR ALL    USING (public.is_admin());


-- ============================================================
-- 14. WITHDRAWAL REQUESTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.withdrawal_requests (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  amount          DECIMAL(12,2) NOT NULL,
  payment_method  TEXT NOT NULL DEFAULT 'bank_transfer',
  payment_details TEXT,
  payment_qr_url  TEXT,
  status          TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_note      TEXT,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  resolved_at     TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

ALTER TABLE public.withdrawal_requests ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Users can insert own withdrawal requests" ON withdrawal_requests;
  DROP POLICY IF EXISTS "Users can read own withdrawal requests"   ON withdrawal_requests;
  DROP POLICY IF EXISTS "Admins manage all withdrawal requests"    ON withdrawal_requests;
END $$;

CREATE POLICY "Users can insert own withdrawal requests" ON withdrawal_requests
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can read own withdrawal requests"  ON withdrawal_requests
  FOR SELECT USING (auth.uid() = user_id OR public.is_admin());
CREATE POLICY "Admins manage all withdrawal requests"   ON withdrawal_requests
  FOR ALL USING (public.is_admin());


-- ============================================================
-- 15. STORAGE BUCKET
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('nexgen-uploads', 'nexgen-uploads', true)
ON CONFLICT (id) DO NOTHING;

DO $$ BEGIN
  DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
  DROP POLICY IF EXISTS "Public can read uploads"        ON storage.objects;
  DROP POLICY IF EXISTS "Owners can delete uploads"      ON storage.objects;
END $$;

CREATE POLICY "Authenticated users can upload" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'nexgen-uploads');

CREATE POLICY "Public can read uploads" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'nexgen-uploads');

CREATE POLICY "Owners can delete uploads" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'nexgen-uploads' AND auth.uid() = owner);


-- ============================================================
-- 16. SYNC views_total FOR EXISTING AUTHORS
-- ============================================================
UPDATE public.profiles p
SET views_total = (
  SELECT COALESCE(SUM(b.views), 0)
  FROM public.blogs b
  WHERE b.author_id = p.id
);


-- ============================================================
-- 17. CRITICAL DATA FIX
-- Any blog with status IS NULL is invisible to public visitors.
-- This sets them all to 'published' so they appear on the homepage.
-- Your real blogs written via the dashboard will now show up.
-- ============================================================
UPDATE public.blogs SET status = 'published' WHERE status IS NULL OR status = '';
